#!/usr/bin/env python3
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]
source='\n'.join(p.read_text(encoding='utf-8') for p in list(root.glob('*.php'))+list((root/'includes').glob('*.php'))+list((root/'assets/css').glob('*.css'))+list((root/'assets/js').glob('*.js')))
trace=(root/'LATEST-PLAN-TRACEABILITY.md').read_text(encoding='utf-8')
future_trace=(root/'FUTURE-SUPERSET-18.md').read_text(encoding='utf-8')
contracts=(root/'includes/class-spd-contracts.php').read_text(encoding='utf-8')
central=[f'CV-{i:03d}' for i in range(14,26)]+[f'CV-{i:03d}' for i in range(239,286)]+['F03-CEN-01','F03-CEN-02']
future=[f'F03-FUT-{i:02d}' for i in range(1,19)]
expected=central+future
assert len(central)==61 and len(future)==18 and len(expected)==79
missing_trace=[x for x in central if f'| {x} |' not in trace]+[x for x in future if f'| {x} |' not in future_trace]
missing_manifest=[x for x in central if f"'{x}'" not in contracts]
# Future IDs are generated by SPD_Future_Profile::requirements; require the generator and boundary endpoints.
if 'F03-FUT-%02d' not in source or 'range( 1, 18 )' not in source:
    missing_manifest += future
if missing_trace or missing_manifest:
    raise SystemExit(f'missing trace={missing_trace}; manifest={missing_manifest}')
checks={
 'personal-site':['personal_site_dto','sabri_profile_personal_site','appointment_url','credential_card'],
 'search':['spd_get_search_projection','sabri_file26_profile_search_projection_v1','search_projection'],
 'share-qr':['ProfileShareLinkRotated.v1','data-spd-qr','qrMatrix','tracking_free'],
 'preview':['sabri_profile_private_preview','spd-preview-frame--mobile','spd-preview-frame--rtl'],
 'delegation':['spd_profile_delegations','delegate_can_manage','clinic_schedule_request'],
 'privacy':['public_extended_fields','audience_allows','no File 03 user-level surveillance store'],
 'safety':['validate_presentation_fields','create_safety_report','child_safety','ProfileReportAppealed.v1'],
 'green':['#087A4E','--sabri-primary'],
 'ownership':['file08','file09','file26','no duplicate truth created'],
 'future-schema':['spd_profile_translations','spd_profile_attestations','spd_profile_future_state','spd_future_schema_version'],
 'credential-wallet':['sabri_file09_verifiable_credentials_v1','credential_wallet'],
 'selective-disclosure':['disclosure_token','DISCLOSURE_MAX_TTL','revocable_with_share_epoch'],
 'learning-passport':['sabri_profile_learning_passport_v1','learning_passport'],
 'trust-timeline':['sabri_profile_trust_timeline_v1','trust_timeline'],
 'expertise-evidence':['sabri_profile_expertise_evidence_v1','expertise_evidence'],
 'knowledge-graph':['sabri_profile_knowledge_graph_v1','knowledge_graph'],
 'knowledge-coverage':['sabri_profile_knowledge_coverage_v1','paid_influence'],
 'grounded-ai':['sabri_file16_grounded_profile_ask_v1','public_professional_work','spd_ai_scope_restricted'],
 'multilingual':['profile_translations','save_translation','machine translated, owner approved'],
 'contact-relay':['sabri_file17_profile_contact_relay_v1','address_hidden'],
 'verified-links':['sabri_verified_external_profile_links_v1','safe_external_url'],
 'dossier':['dossier','Structured Professional Dossier'],
 'embed':['embed_card','script_required','tracking'],
 'freshness':['profile_attestations','reconfirm_field','ProfileFieldReconfirmed.v1'],
 'change-history':['change_history','ProfileTranslationUpdated.v1','ProfileFutureStateChanged.v1'],
 'lifecycle':['professional_lifecycle','legacy','active_professional'],
 'fhir':['resourceType','PractitionerRole','clinical_record'],
 'federation':['federation_opt_in','sabri_federation_actor_transport_v1','transport_active'],
 'future-idempotency':['future_idempotency_begin','Idempotency-Key','create_selective_disclosure'],
 'future-privacy':['SPD_Future_Privacy','wp_privacy_personal_data_exporters','profile_future_state'],
}
missing=[]
combined='\n'.join((source, trace, future_trace, contracts))
for name,tokens in checks.items():
    for token in tokens:
        if token not in combined:
            missing.append(f'{name}:{token}')
if missing: raise SystemExit('Latest-plan/future coverage gaps:\n'+'\n'.join(missing))
if re.search(r'https://(?:chart\.googleapis|api\.qrserver|quickchart)', source, re.I):
    raise SystemExit('Third-party QR/tracking dependency detected')
if re.search(r'paid[_ -]?(?:boost|rank|verification)|donor[_ -]?(?:boost|rank)', source, re.I):
    raise SystemExit('Paid/donor profile advantage detected')
print(f'Latest governing coverage passed: {len(central)} central IDs + {len(future)} future IDs = {len(expected)} additive IDs, plus native ownership guards.')
